server:
  port: 8080
spring:
  datasource:
    username: root
    password: xzjroot
    url: jdbc:mysql://localhost:3306/slump?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
