server:
  port: 8088
  servlet:
    context-path: '/slump'
spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/slump?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
