spring:
  datasource:
    username: root
    password: xzjroot
    url: jdbc:mysql://localhost:3306/slump?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver